import fs from 'fs';
const p = 'engineering/packages/kit-matching/src/catalogue/components.ts';
let content = fs.readFileSync(p, 'utf-8');

const additions = `
  // --- New Research Bundle Components ---

  component({
    id: 'battery-lipo-3s',
    name: '3S LiPo Battery Module (11.1V)',
    family: 'battery',
    partFamily: 'LiPo',
    satisfiesNodeType: 'battery',
    electrical: {
      supplyVoltageMinV: 11.1, supplyVoltageMaxV: 12.6,
      typicalCurrentMa: 0, envelopeSource: 'GENERIC_FAMILY',
    },
    providesCapabilities: { 'battery.present': true, 'power.available': true },
    notes: 'For driving stepper motors and 12V loads.',
  }),
  component({
    id: 'controller-linux',
    name: 'Embedded Linux application processor',
    family: 'controller',
    partFamily: 'ARM Cortex-A',
    satisfiesNodeType: 'controller',
    electrical: {
      supplyVoltageMinV: 4.5, supplyVoltageMaxV: 5.5,
      typicalCurrentMa: 1500, envelopeSource: 'GENERIC_FAMILY',
    },
    providesCapabilities: { 'controller.present': true, 'compute.present': true },
    notes: 'Needs heavy power rail.',
  }),
  component({
    id: 'controller-flight',
    name: 'Flight controller board',
    family: 'controller',
    partFamily: null,
    satisfiesNodeType: 'controller',
    electrical: {
      supplyVoltageMinV: 4.5, supplyVoltageMaxV: 5.5,
      typicalCurrentMa: 500, envelopeSource: 'GENERIC_FAMILY',
    },
    providesCapabilities: { 'controller.present': true, 'compute.present': true },
    notes: '',
  }),
  component({
    id: 'controller-riscv',
    name: 'RISC-V edge compute board',
    family: 'controller',
    partFamily: 'RISC-V',
    satisfiesNodeType: 'controller',
    electrical: {
      supplyVoltageMinV: 4.5, supplyVoltageMaxV: 5.5,
      typicalCurrentMa: 800, envelopeSource: 'GENERIC_FAMILY',
    },
    providesCapabilities: { 'controller.present': true, 'compute.present': true },
    notes: '',
  }),
  component({
    id: 'controller-ros2',
    name: 'ROS2 compute node',
    family: 'controller',
    partFamily: null,
    satisfiesNodeType: 'controller',
    electrical: {
      supplyVoltageMinV: 4.5, supplyVoltageMaxV: 5.5,
      typicalCurrentMa: 2000, envelopeSource: 'GENERIC_FAMILY',
    },
    providesCapabilities: { 'controller.present': true, 'compute.present': true },
    notes: '',
  }),
  component({
    id: 'driver-stepper',
    name: 'Stepper motor driver',
    family: 'motor-driver',
    partFamily: null,
    satisfiesNodeType: 'driver',
    electrical: {
      supplyVoltageMinV: 8.0, supplyVoltageMaxV: 35.0,
      typicalCurrentMa: 15, envelopeSource: 'GENERIC_FAMILY',
    },
    providesCapabilities: { 'driver.stepper': true, 'driver.channels': 1 },
    notes: '',
  }),
  component({
    id: 'motor-stepper',
    name: 'NEMA17 Stepper motor',
    family: 'motor',
    partFamily: 'NEMA17',
    satisfiesNodeType: 'motor',
    electrical: {
      supplyVoltageMinV: 8.0, supplyVoltageMaxV: 35.0,
      typicalCurrentMa: 1500, envelopeSource: 'GENERIC_FAMILY',
    },
    providesCapabilities: { 'motor.count': 1, 'motion.present': true },
    notes: '',
  }),
  component({
    id: 'actuator-contactor',
    name: 'High-current contactor',
    family: 'actuator',
    partFamily: null,
    satisfiesNodeType: null,
    electrical: {
      supplyVoltageMinV: 11.0, supplyVoltageMaxV: 14.0,
      typicalCurrentMa: 250, envelopeSource: 'GENERIC_FAMILY',
    },
    providesCapabilities: { 'actuator.switch': true },
    notes: '',
  }),
  component({
    id: 'sensor-current',
    name: 'Current sensor module',
    family: 'sensor',
    partFamily: null,
    satisfiesNodeType: 'sensor',
    electrical: {
      supplyVoltageMinV: 3.0, supplyVoltageMaxV: 5.5,
      typicalCurrentMa: 10, envelopeSource: 'GENERIC_FAMILY',
    },
    providesCapabilities: { 'sensor.count': 1, 'sensing.present': true },
    notes: '',
  }),
  component({
    id: 'mechanical-quadruped-chassis',
    name: 'Quadruped robot chassis',
    family: 'mechanical',
    partFamily: null,
    satisfiesNodeType: null,
    electrical: null,
    providesCapabilities: { 'mechanical.chassis': true },
    notes: '',
  }),
  component({
    id: 'mechanical-gantry',
    name: 'Gantry hardware set',
    family: 'mechanical',
    partFamily: null,
    satisfiesNodeType: null,
    electrical: null,
    providesCapabilities: { 'mechanical.chassis': true },
    notes: '',
  }),
  component({
    id: 'mechanical-corexy',
    name: 'CoreXY hardware set',
    family: 'mechanical',
    partFamily: null,
    satisfiesNodeType: null,
    electrical: null,
    providesCapabilities: { 'mechanical.chassis': true },
    notes: '',
  }),
  component({
    id: 'mechanical-microscope-stage',
    name: 'Microscope translation stage',
    family: 'mechanical',
    partFamily: null,
    satisfiesNodeType: null,
    electrical: null,
    providesCapabilities: { 'mechanical.chassis': true },
    notes: '',
  }),
  component({
    id: 'mechanical-recycling-shredder',
    name: 'Plastic shredder mechanicals',
    family: 'mechanical',
    partFamily: null,
    satisfiesNodeType: null,
    electrical: null,
    providesCapabilities: { 'mechanical.chassis': true },
    notes: '',
  }),
  component({
    id: 'radio-sdr',
    name: 'Software defined radio receiver',
    family: 'connectivity',
    partFamily: null,
    satisfiesNodeType: 'connectivity',
    electrical: {
      supplyVoltageMinV: 4.5, supplyVoltageMaxV: 5.5,
      typicalCurrentMa: 300, envelopeSource: 'GENERIC_FAMILY',
    },
    providesCapabilities: { 'link.present': true },
    notes: '',
  }),
  component({
    id: 'camera-global-shutter',
    name: 'Global shutter camera module',
    family: 'sensor',
    partFamily: null,
    satisfiesNodeType: 'sensor',
    electrical: {
      supplyVoltageMinV: 3.0, supplyVoltageMaxV: 5.5,
      typicalCurrentMa: 150, envelopeSource: 'GENERIC_FAMILY',
    },
    providesCapabilities: { 'sensing.present': true, 'vision.present': true },
    notes: '',
  }),
`;

content = content.replace('];\n\nconst BY_ID', additions + '];\n\nconst BY_ID');
fs.writeFileSync(p, content, 'utf-8');
