export const LH_ERROR_CODES = {
  LH_PROJECT_NOT_FOUND:          { code: 'LH_PROJECT_NOT_FOUND',          retryable: false },
  LH_REPOSITORY_INVALID:         { code: 'LH_REPOSITORY_INVALID',         retryable: false },
  LH_REPOSITORY_DIRTY:           { code: 'LH_REPOSITORY_DIRTY',           retryable: true  },
  LH_GIT_REF_NOT_FOUND:          { code: 'LH_GIT_REF_NOT_FOUND',          retryable: false },
  LH_GIT_ANCESTRY_INVALID:       { code: 'LH_GIT_ANCESTRY_INVALID',       retryable: false },
  LH_REVISION_NOT_FOUND:         { code: 'LH_REVISION_NOT_FOUND',         retryable: false },
  LH_REVISION_IMMUTABLE:         { code: 'LH_REVISION_IMMUTABLE',         retryable: false },
  LH_REVISION_STALE:             { code: 'LH_REVISION_STALE',             retryable: true  },
  LH_SCHEMA_INVALID:             { code: 'LH_SCHEMA_INVALID',             retryable: false },
  LH_ENGINEERING_OBJECT_INVALID: { code: 'LH_ENGINEERING_OBJECT_INVALID', retryable: false },
  LH_KICAD_PROJECT_INVALID:      { code: 'LH_KICAD_PROJECT_INVALID',      retryable: false },
  LH_KICAD_VERSION_UNSUPPORTED:  { code: 'LH_KICAD_VERSION_UNSUPPORTED',  retryable: false },
  LH_KICAD_IMPORT_FAILED:        { code: 'LH_KICAD_IMPORT_FAILED',        retryable: true  },
  LH_ERC_FAILED:                 { code: 'LH_ERC_FAILED',                 retryable: true  },
  LH_DRC_FAILED:                 { code: 'LH_DRC_FAILED',                 retryable: true  },
  LH_CONSTRAINT_VIOLATION:       { code: 'LH_CONSTRAINT_VIOLATION',       retryable: false },
  LH_VALIDATION_REQUIRED:        { code: 'LH_VALIDATION_REQUIRED',        retryable: false },
  LH_VALIDATION_FAILED:          { code: 'LH_VALIDATION_FAILED',          retryable: true  },
  LH_ARTIFACT_HASH_MISMATCH:     { code: 'LH_ARTIFACT_HASH_MISMATCH',     retryable: false },
  LH_ARTIFACT_NOT_FOUND:         { code: 'LH_ARTIFACT_NOT_FOUND',         retryable: false },
  LH_DECISION_REQUIRED:          { code: 'LH_DECISION_REQUIRED',          retryable: false },
  LH_REVIEW_REQUIRED:            { code: 'LH_REVIEW_REQUIRED',            retryable: false },
  LH_CHANGES_REQUESTED:          { code: 'LH_CHANGES_REQUESTED',          retryable: false },
  LH_MERGE_BLOCKED:              { code: 'LH_MERGE_BLOCKED',              retryable: false },
  LH_STATE_TRANSITION_INVALID:   { code: 'LH_STATE_TRANSITION_INVALID',   retryable: false },
  LH_TIMEOUT:                    { code: 'LH_TIMEOUT',                    retryable: true  },
  LH_RESOURCE_LIMIT:             { code: 'LH_RESOURCE_LIMIT',             retryable: true  },
  LH_INTERNAL_ERROR:             { code: 'LH_INTERNAL_ERROR',             retryable: false },
} as const;

export type LHErrorCode = keyof typeof LH_ERROR_CODES;
