// LogicHub/scripts/build-seo.mjs
// Generates sitemap.xml and robots.txt from the pages that actually ship.
//
// robots.txt already pointed at https://logichub.app/sitemap.xml, and that file
// did not exist. Rather than hand-writing one that would drift the moment a page
// was added, the list is read from the built output — so a new policy page
// cannot be forgotten, because forgetting it would mean not building it.
//
// robots.txt is generated here too, so the sitemap line and the crawler rules
// stay in one place. The AI-crawler blocks are the deliberate position of this
// project: the design tooling exists so that work does not pass through someone
// else's model, and the marketing site should not either.
//
// Run: node scripts/build-seo.mjs

import { readdirSync, writeFileSync, copyFileSync, existsSync, mkdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { SITE_ORIGIN } from './site-constants.mjs';

/**
 * Pages that exist but should not be listed.
 *
 * A page is excluded because being indexed would be wrong for it, not because
 * it is unimportant.
 */
const EXCLUDE = new Set([
  '404.html',
  'offline.html',
]);

/** Relative priority. Anything unlisted gets the default. */
const PRIORITY = {
  '/': '1.0',
  '/product-builder': '0.9',
  '/waitlist': '0.8',
  '/onboarding': '0.7',
};
const DEFAULT_PRIORITY = '0.5';

/** Crawlers that train on what they read. */
const AI_CRAWLERS = [
  'GPTBot',
  'ChatGPT-User',
  'ClaudeBot',
  'anthropic-ai',
  'Claude-Web',
  'CCBot',
  'Bytespider',
  'PerplexityBot',
  'Google-Extended',
  'Applebot-Extended',
  'Meta-ExternalAgent',
  'cohere-ai',
  'Diffbot',
  'Omgilibot',
];

function pagePath(file) {
  if (file === 'index.html') return '/';
  // cleanUrls is on in vercel.json, so the canonical address has no extension.
  return `/${file.replace(/\.html$/, '')}`;
}

/**
 * Last modification date, taken from git.
 *
 * If git cannot answer, the entry simply has no lastmod. Substituting today's
 * date would tell a crawler that every page changed on every build, which is a
 * claim about the content that the build has no basis for.
 */
function lastModified(file) {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cs', '--', file], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(out) ? out : null;
  } catch {
    return null;
  }
}

const files = readdirSync('.')
  .filter((name) => name.endsWith('.html') && !EXCLUDE.has(name))
  .sort();

if (existsSync('public/tools')) {
  try {
    const toolsFolders = readdirSync('public/tools', { withFileTypes: true })
      .filter(dirent => dirent.isDirectory() && dirent.name.startsWith('tool-'))
      .map(dirent => `tools/${dirent.name}.html`);
    
    files.push('tools.html');
    files.push(...toolsFolders);
  } catch (e) {}
}

const entries = files.map((file) => {
  const path = pagePath(file);
  return {
    file,
    loc: `${SITE_ORIGIN}${path}`,
    lastmod: lastModified(file),
    priority: PRIORITY[path] || DEFAULT_PRIORITY,
  };
});

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...entries.map((entry) => [
    '  <url>',
    `    <loc>${entry.loc}</loc>`,
    ...(entry.lastmod ? [`    <lastmod>${entry.lastmod}</lastmod>`] : []),
    `    <priority>${entry.priority}</priority>`,
    '  </url>',
  ].join('\n')),
  '</urlset>',
  '',
].join('\n');

const robots = [
  '# Generated by scripts/build-seo.mjs. Edit that, not this.',
  '',
  'User-agent: *',
  'Allow: /',
  '',
  '# Blocked deliberately. This project exists so that a design does not have to',
  '# pass through someone else\'s model to be useful, and the site that explains it',
  '# is not training material either.',
  ...AI_CRAWLERS.flatMap((agent) => ['', `User-agent: ${agent}`, 'Disallow: /']),
  '',
  `Sitemap: ${SITE_ORIGIN}/sitemap.xml`,
  '',
].join('\n');

if (!existsSync('public')) mkdirSync('public', { recursive: true });

for (const [name, content] of [['sitemap.xml', sitemap], ['robots.txt', robots]]) {
  writeFileSync(name, content);
  copyFileSync(name, `public/${name}`);
}

console.log(JSON.stringify({
  pages: entries.map((entry) => entry.loc),
  withLastmod: entries.filter((entry) => entry.lastmod).length,
  blockedCrawlers: AI_CRAWLERS.length,
}, null, 2));
